### ISSUE TITLE
Provide mechanism to use a Galaxy callback for data downloads

### ISSUE THREAD

**Issue by bcorrie** [ireceptor-plus/WP1#11]
As per the discussion around iReceptor Gateway and ImmuneML Galaxy, we want to implement the ability for Galaxy to send a Galaxy user to the iReceptor downloads page with a Galaxy callback URL. The Gateway will allow the user to choose a data set from their downloads and then use the Galaxy callback URL to notify Galaxy where the data is so Galaxy can download it...

**Comment by schristley** [comment]
moved to [here](https://github.com/ireceptor-plus/specifications/issues/15) as an experiment
