### ISSUE TITLE
Determine Gateway -> Stats interface

### ISSUE THREAD

**Issue by bcorrie** [ireceptor-plus/WP1#9]
Current working assumption is that the Stats JS code is run on a page, and the page will have something like the following (minimally):

```
<script>
	var statsHTMLBlock = "draw_stats_here";
        /* stats_json Provided by the Gateway based on Stats queries */
        var statsJSONData = {!! $stats_json !!};
</script>
```
This would result in some graphs of the data in stats_json being drawn in the DIV block with the label "draw_stats_here"

What else is required???

**Comment by marcoamarooliveira** [comment]
@bcorrie, see this http://jsfiddle.net/arievilo/tcuwez0o

**Comment by bcorrie** [comment]
It feels to me like we need `$stats_json` to be a bit more comprehensive than what is simply returned from the Stats API.

The Gateway will probably want to ask the visualization to use specific labels for each stat (e.g. I want the V Gene usage graph to have the title "v gene usage") as well labels for each dimension of the graph (e.g. "v gene count" for the count axis and "v gene" for the axis where the the thing that is counted resides.

**Comment by bcorrie** [comment]
> @bcorrie, see this http://jsfiddle.net/arievilo/tcuwez0o

Sweet!

**Comment by bcorrie** [comment]
@marcoamarooliveira would you be able to share your JS code that you mentioned today and describe the architecture you are thinking of. We are interested in understanding how the UI platforms such as the iReceptor Gateway, VDJServer etc might reuse this code as well as try and understand how we can port some of the already existing visualization work that has been performed to use the middleware you mentioned today.

**Comment by schristley** [comment]
@marcoamarooliveira my suggestion is we setup a irplus github repository with a npm javascript module. That's certainly the easiest way for VDJServer to integrate, not sure about the other UIs.

**Comment by bcorrie** [comment]
Closing this as replicated elsewhere.
